<?php

$title = 'User';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>

<p><?php echo $this->layout()->sharedHeadline . $this->layout()->pi ?></p>

<p>
    <a href="<?php echo $this->url('user', array('action'=>'add'));?>">Add new user</a>
</p>

<table class="table">
    <tr>
        <th>Username</th>
        <th>Password</th>
        <th>Role</th>
        <th>&nbsp;</th>
    </tr>
    <?php foreach ($users as $user) : ?>
        <tr>
            <td><?php echo $this->escapeHtml($user->username);?></td>
            <td><?php echo $this->escapeHtml($user->password);?></td>
            <td><?php echo $this->escapeHtml($user->role);?></td>
            <td>
                <a href="<?php echo $this->url('user', ['action'=>'edit', 'id' => $user->id]);?>">Edit</a>
                <a href="<?php echo $this->url('user', ['action'=>'delete', 'id' => $user->id]);?>">Delete</a>
            </td>
        </tr>
    <?php endforeach; ?>
</table>