<?php

$title = 'My favorite albums';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>

<?php if ($this->acl()->isCurrentUserAllowed('User\Controller\User::add')): ?>
    <p>
        <a href="<?php echo $this->url('album', array('action' => 'add')); ?>">Add new user</a>
    </p>
<?php endif; ?>

<table class="table">
    <tr>
        <th>Title</th>
        <th>Artist</th>
        <th>&nbsp;</th>
    </tr>
    <?php foreach ($albums as $album) : ?>
        <tr>
            <td><?php echo $this->escapeHtml($album->title); ?></td>
            <td><?php echo $this->escapeHtml($album->artist); ?></td>
            <td>
                <?php if ($this->acl()->isCurrentUserAllowed('Album\Controller\Album::edit')): ?>
                    <a href="<?php echo $this->url('album', ['action' => 'edit', 'id' => $album->id]); ?>">Edit</a>
                <?php endif; ?>
                <?php if ($this->acl()->isCurrentUserAllowed('Album\Controller\Album::delete')): ?>
                    <a href="<?php echo $this->url('album', ['action' => 'delete', 'id' => $album->id]); ?>">Delete</a>
                <?php endif; ?>
            </td>
        </tr>
    <?php endforeach; ?>
</table>